/*
 Navicat Premium Data Transfer

 Source Server         : test
 Source Server Type    : Oracle
 Source Server Version : 190000
 Source Host           : localhost:1521
 Source Schema         : C##MAY

 Target Server Type    : Oracle
 Target Server Version : 190000
 File Encoding         : 65001

 Date: 09/08/2022 17:28:22
*/


-- ----------------------------
-- Table structure for GOALS
-- ----------------------------
DROP TABLE "C##MAY"."GOALS";
CREATE TABLE "C##MAY"."GOALS" (
  "USER_ID" NUMBER VISIBLE,
  "CALORIE_INTAKE_GOAL" FLOAT(126) VISIBLE,
  "CALORIE_BURN_GOAL" FLOAT(126) VISIBLE,
  "WATER_INTAKE_GOAL" NUMBER VISIBLE,
  "CARB_GOAL" NUMBER VISIBLE,
  "PROTEIN_GOAL" NUMBER VISIBLE,
  "FAT_GOAL" NUMBER VISIBLE,
  "VITAMIN_C" NUMBER VISIBLE,
  "IRON" NUMBER VISIBLE,
  "SODIUM" NUMBER VISIBLE,
  "SUGAR" NUMBER VISIBLE,
  "DIETARY_FIBER" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of GOALS
-- ----------------------------
INSERT INTO "C##MAY"."GOALS" VALUES ('6', '1310.84993548387', '150', '8', '40', '30', '30', '75', '15', '2300', '20', '25');
INSERT INTO "C##MAY"."GOALS" VALUES ('3', '1595.80206451613', '150', '8', '40', '30', '30', '75', '15', '2300', '20', '25');

-- ----------------------------
-- Table structure for USERS
-- ----------------------------
DROP TABLE "C##MAY"."USERS";
CREATE TABLE "C##MAY"."USERS" (
  "USER_ID" NUMBER VISIBLE NOT NULL,
  "USERNAME" VARCHAR2(100 BYTE) VISIBLE NOT NULL,
  "FIRST_NAME" VARCHAR2(50 BYTE) VISIBLE,
  "LAST_NAME" VARCHAR2(50 BYTE) VISIBLE,
  "WEIGHT" FLOAT(126) VISIBLE,
  "HEIGHT" FLOAT(126) VISIBLE,
  "DATE_OF_BIRTH" VARCHAR2(50 BYTE) VISIBLE,
  "GENDER" CHAR(1 BYTE) VISIBLE,
  "EMAIL" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "PASSWORD" VARCHAR2(32 BYTE) VISIBLE NOT NULL,
  "BMI" NUMBER(4,2) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of USERS
-- ----------------------------
INSERT INTO "C##MAY"."USERS" VALUES ('6', '1905103', 'Mayesha', 'Rashid', '83', '63', '15-Nov-1999', 'F', 'mayesha1599@gmail.com', 'abcd', '32.41');
INSERT INTO "C##MAY"."USERS" VALUES ('3', 'zm_99', 'Alina', 'Zaman', '52', '60', '05-Apr-2000', 'F', 'alina@hotmail.com', '1234', '22.39');

-- ----------------------------
-- Sequence structure for USER_SEQUENCE
-- ----------------------------
DROP SEQUENCE "C##MAY"."USER_SEQUENCE";
CREATE SEQUENCE "C##MAY"."USER_SEQUENCE" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Primary Key structure for table USERS
-- ----------------------------
ALTER TABLE "C##MAY"."USERS" ADD CONSTRAINT "SYS_C008049" PRIMARY KEY ("USER_ID");

-- ----------------------------
-- Uniques structure for table USERS
-- ----------------------------
ALTER TABLE "C##MAY"."USERS" ADD CONSTRAINT "SYS_C008050" UNIQUE ("USERNAME") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##MAY"."USERS" ADD CONSTRAINT "SYS_C008051" UNIQUE ("EMAIL") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table USERS
-- ----------------------------
ALTER TABLE "C##MAY"."USERS" ADD CONSTRAINT "SYS_C008046" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##MAY"."USERS" ADD CONSTRAINT "SYS_C008047" CHECK ("EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##MAY"."USERS" ADD CONSTRAINT "SYS_C008048" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table USERS
-- ----------------------------
CREATE TRIGGER "C##MAY"."ADD_GOAL" AFTER INSERT ON "C##MAY"."USERS" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
DECLARE BMR FLOAT;
BEGIN
IF :NEW.GENDER ='F'
THEN
--DBMS_OUTPUT.PUT_LINE(:NEW.GENDER);
BMR:=1.2*(655.1+(9.563* :NEW.WEIGHT)+(1.85*2.54* :NEW.HEIGHT)-4.676*(MONTHS_BETWEEN(TRUNC(SYSDATE),TO_DATE(:NEW.DATE_OF_BIRTH,'DD-MON-YYYY'))/12));
ELSE
--DBMS_OUTPUT.PUT_LINE(:NEW.GENDER);
BMR:=1.2*(66.47+(13.75*:NEW.WEIGHT)+(5.003*2.54*:NEW.HEIGHT)-6.755*(MONTHS_BETWEEN(TRUNC(SYSDATE),TO_DATE(:NEW.DATE_OF_BIRTH,'DD-MON-YYYY'))/12));
END IF;
IF :NEW.BMI>25
THEN
	BMR:=2*BMR/3;
END IF;
INSERT INTO GOALS(USER_ID,CALORIE_INTAKE_GOAL,CALORIE_BURN_GOAL,WATER_INTAKE_GOAL,CARB_GOAL,PROTEIN_GOAL,FAT_GOAL,VITAMIN_C,IRON,SODIUM,SUGAR,DIETARY_FIBER)
VALUES(:NEW.USER_ID,BMR,150,8,40,30,30,75,15,2300,20,25);
--DBMS_OUTPUT.PUT_LINE('HOISE');
END;
/
CREATE TRIGGER "C##MAY"."USER_BIN" BEFORE INSERT ON "C##MAY"."USERS" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
IF :NEW.USER_ID IS NULL
THEN
:NEW.USER_ID:=USER_SEQUENCE.NEXTVAL;
END IF;
END;


--DROP SEQUENCE USER_SEQUENCE;
