--trigger1
CREATE or REPLACE TRIGGER USER_BIN
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
IF :NEW.USER_ID IS NULL
THEN
:NEW.USER_ID:=USER_SEQUENCE.NEXTVAL;
END IF;
END;

--trigger2
CREATE OR REPLACE TRIGGER ADD_CALORIE_GOAL
AFTER INSERT
ON USERS
FOR EACH ROW
DECLARE BMR FLOAT;
AGE INTEGER;
WATER INTEGER;
BEGIN
IF :NEW.GENDER ='F'
THEN
--DBMS_OUTPUT.PUT_LINE(:NEW.GENDER);
BMR:=1.2*(655.1+(9.563* :NEW.WEIGHT)+(1.85*2.54* :NEW.HEIGHT)-4.676*(MONTHS_BETWEEN(TRUNC(SYSDATE),TO_DATE(:NEW.DATE_OF_BIRTH,'DD-MON-YYYY'))/12));
ELSE
--DBMS_OUTPUT.PUT_LINE(:NEW.GENDER);
BMR:=1.2*(66.47+(13.75*:NEW.WEIGHT)+(5.003*2.54*:NEW.HEIGHT)-6.755*(MONTHS_BETWEEN(TRUNC(SYSDATE),TO_DATE(:NEW.DATE_OF_BIRTH,'DD-MON-YYYY'))/12));
END IF;
IF :NEW.DESIRE=1 THEN
	BMR:=(2*BMR)/3;
ELSIF :NEW.DESIRE=2 THEN
	BMR:=(4*BMR)/3;
END IF;

AGE:=MONTHS_BETWEEN(TRUNC(SYSDATE),TO_DATE(:NEW.DATE_OF_BIRTH,'DD-MON-YYYY'))/12;
IF AGE<=13 THEN
WATER:=8;
ELSIF AGE<=18 THEN
WATER:=10;
ELSIF :NEW.GENDER='F' THEN
WATER:=9;
ELSE
WATER:=13;
END IF;


INSERT INTO GOALS(USER_ID,CALORIE_INTAKE_GOAL,WATER_INTAKE_GOAL)
VALUES(:NEW.USER_ID,BMR,WATER);

END;

--trigger3
CREATE OR REPLACE TRIGGER MEAL_TRIG
BEFORE INSERT ON MEAL_LOGGER
FOR EACH ROW
BEGIN
IF :NEW.MEAL_ID IS NULL
THEN
:NEW.MEAL_ID:=MEAL_SEQUENCE.NEXTVAL;
END IF;
END;

--trigger4
CREATE OR REPLACE TRIGGER ELOG_TRIG
BEFORE INSERT ON EXERCISE_LOG
FOR EACH ROW
BEGIN
IF :NEW.ELOG_ID IS NULL
THEN
:NEW.ELOG_ID:=ELOG_SEQUENCE.NEXTVAL;
END IF;
END;

--trigger5
CREATE OR REPLACE TRIGGER UPDATE_CALORIE
AFTER UPDATE
ON USERS
FOR EACH ROW
DECLARE BMR NUMBER(6,2);
BEGIN
IF :NEW.GENDER ='F'
THEN
--DBMS_OUTPUT.PUT_LINE(:NEW.GENDER);
BMR:=1.2*(655.1+(9.563* :NEW.WEIGHT)+(1.85*2.54* :NEW.HEIGHT)-4.676*(MONTHS_BETWEEN(TRUNC(SYSDATE),TO_DATE(:NEW.DATE_OF_BIRTH,'DD-MON-YYYY'))/12));
ELSE
--DBMS_OUTPUT.PUT_LINE(:NEW.GENDER);
BMR:=1.2*(66.47+(13.75*:NEW.WEIGHT)+(5.003*2.54*:NEW.HEIGHT)-6.755*(MONTHS_BETWEEN(TRUNC(SYSDATE),TO_DATE(:NEW.DATE_OF_BIRTH,'DD-MON-YYYY'))/12));
END IF;
IF :NEW.DESIRE=1 THEN
	BMR:=(2*BMR)/3;
ELSIF :NEW.DESIRE=2 THEN
	BMR:=(4*BMR)/3;
END IF;
UPDATE GOALS
SET CALORIE_INTAKE_GOAL=BMR
WHERE USER_ID=:NEW.USER_ID;
END;
